name: IDzEE Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
      - ARM64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar ambiente
        run: |
          hostname
          node --version
          zowe --version

      - name: Executar build no z/OS
        env:
          ZOS_HOST: ${{ secrets.ZOS_HOST }}
          ZOS_PORT: ${{ secrets.ZOS_PORT }}
          ZOS_USER: ${{ secrets.ZOS_USER }}
          ZOS_PASSWORD: ${{ secrets.ZOS_PASSWORD }}
        run: |
          zowe rse issue unix \
            "/u/b027086/ci/build.sh" \
            --host "$ZOS_HOST" \
            --port "$ZOS_PORT" \
            --base-path rseapi \
            --protocol https \
            --reject-unauthorized false \
            --user "$ZOS_USER" \
            --password "$ZOS_PASSWORD"